<?php
use app\components\grid\TGridView;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\modules\pms\models\Task;
use app\models\User;
use app\modules\pms\models\OpexBudget;
use app\modules\pms\models\Finance;
use app\modules\pms\models\Project;
use app\modules\pms\models\search\Rate;
use yii\helpers\VarDumper;
use app\modules\pms\models\Rename;
use app\modules\pms\models\Variable;
/**
 *
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\modules\pms\models\search\Finance $searchModel
 */
?>
<?php
$variable = Variable::variable();
?>
<div class="w-100 d-flex justify-content-center banner-imgs">
<?php

echo Html::img(yii::$app->view->theme->getUrl('admin/img/calculation.jpg'), []);
?>


</div>
<ul class="list-unstyled d-flex">
	<li class="mr-3 w-25">
		<div class="border p-2 rounded-lg">
			<span>Annual Discount Rate :</span>
<?php
$model = \app\modules\pms\models\Rate::find()->where([
    'project_id' => Yii::$app->request->queryParams['id']
])->one();
if (! empty($model)) {
    echo $model->rate;
    $title = "Update Rate";
    $url = [
        'rate/update',
        'id' => $model->id
    ];
} else {
    $title = "Add Rate";
    $url = [
        'rate/add',
        'id' => Yii::$app->request->queryParams['id']
    ];
}
?>
</div>
	</li>
	<li> 
  
<?php
echo Html::a($title, $url, [
    'class' => 'btn btn-success mt-1'
]);

?>
   </li>
</ul>



<div class="row">
	<div class="col-12">
<?php
if (! empty($menu))
    echo Html::a($menu['label'], $menu['url'], [
        'class' => ' btn btn-success pull-right'
    ]);
?>
<h4 class="my-2 blue-back"><?=empty($variable['npv']->title) ? 'NPV' : $variable['npv']->title?></h4>
<?php

Pjax::begin([
    'id' => 'finance-pjax-ajax-grid',
    'enablePushState' => false,
    'enableReplaceState' => false
]);
?>

    <?php

    echo TGridView::widget([
        'summary' => false,
        'enableRowClick' => false,
        'id' => 'finance-ajax-grid-view',
        'dataProvider' => $dataProvider,
        'tableOptions' => [
            'class' => 'table custom-table mt-3'
        ],
        'columns' => [

            [
                'attribute' => 'time',

                'label' => empty($variable['period']->title) ? 'T Period' : $variable['period']->title
            ],

            [
                'attribute' => 'income',
                'value' => function ($data) {
                    return $data->project->currency . $data->income;
                },
                'label' => empty($variable['income']->title) ? 'Income' : $variable['income']->title
            ],
            [
                'attribute' => 'opex',
                'value' => function ($data) {
                    return $data->project->currency . $data->opex;
                },
                'label' => empty($variable['opex']->title) ? 'Opex' : $variable['opex']->title
            ],
            [
                'attribute' => 'cash_flow',
                'value' => function ($data) {
                    return $data->getTotalCashFlow();
                },
                'label' => empty($variable['cf']->title) ? 'CF' : $variable['cf']->title
            ],
            [
                'class' => 'app\components\TActionColumn',
                'template' => '{update} {delete}',
                'header' => '<a>Actions</a>'
            ]
        ]
    ]);
    ?>
<?php

Pjax::end();
?>
   </div>
	<div class="col-12">
		<h4 class="my-3 blue-back"><?=empty($variable['calculation']->title) ? 'Calculation Results' : $variable['calculation']->title?></h4>
		<div class="table-responsive table-finance">
			<table class="table table-hover m-b-0">
				<thead class="thead-dark">
					<tr>
						<th></th>
						<th><?=empty($variable['description']->title) ? 'Description' : $variable['description']->title?></th>
						<th>Value</th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<th><?=empty($variable['npv']->title) ? 'NPV' : $variable['npv']->title?></th>
						<td><p>A positive net present value indicates that the project
								earnings generated by a project or investment - in present
								dollars - exceeds the anticipated costs, also in present
								dollars. It is assumed that an investment with a positive NPV
								will be profitable, and an investment with a negative NPV will
								result in a net loss.</p></td>
						<td> <?php
    $project = Project::findOne(Yii::$app->request->queryParams['id']);
    if (! empty($project)) {
        echo $project->currency . Finance::getNpv();
    }
    ?>
                                                                        </td>
					</tr>
					<tr>
						<th><?=empty($variable['roi']->title) ? 'ROI' : $variable['roi']->title?></th>
						<td><p>
								Return on investment (ROI) is a financial metric that is widely
								used to measure the probability of gaining a return from an
								investment. It is a ratio that compares the gain or loss from an
								investment relative to its cost.It is as useful in evaluating
								the potential return from a stand-alone investment as it is in
								comparing returns from several investments.</br>For example,
							</p>
							<ul class="pl-3">
								<li>If ROI = 140%, you will make 40$ from 100$ of Investment</li>
								<li>If ROI =80%, you will lose 20$ from 100$ of Investment</li>
							</ul></td>
						<td> <?php
    echo Finance::getRoi();
    ?>
                                                                        </td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>