<?php
use app\components\grid\TGridView;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\modules\pms\models\Task;
use app\models\User;
use app\modules\pms\models\OpexBudget;
use app\modules\pms\models\Finance;
use app\modules\pms\models\Project;
use app\modules\pms\models\search\Rate;
use yii\helpers\VarDumper;
/**
 *
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\modules\pms\models\search\Finance $searchModel
 */
?>
<div class="w-100 d-flex justify-content-center banner-imgs">
<?php

echo Html::img(yii::$app->view->theme->getUrl('admin/img/calculation.jpg'), []);
?>
</div>
<ul class="list-unstyled d-flex">
	<li class="mr-3 w-25">
		<div class="border p-2 rounded-lg">
			<span><?=Yii::t('app', 'Annual Discount Rate')?> :</span>
<?php
$model = \app\modules\pms\models\Rate::find()->where([
    'project_id' => Yii::$app->request->queryParams['id']
])->one();
if (! empty($model)) {
    echo $model->rate;
    $title = Yii::t('app', "Update Rate");
    $url = [
        'rate/update',
        'id' => $model->id
    ];
} else {
    $title = Yii::t('app', "Add Rate");
    $url = [
        'rate/add',
        'id' => Yii::$app->request->queryParams['id']
    ];
}
?>
</div>
	</li>
	<li> 
  
<?php
echo Html::a($title, $url, [
    'class' => 'btn btn-success mt-1'
]);

?>
   </li>
</ul>



<div class="row">
	<div class="col-12">
<?php
if (! empty($menu))
    echo Html::a($menu['label'], $menu['url'], [
        'class' => ' btn btn-success pull-right'
    ]);
?>
<h4 class="my-2 blue-back"><?=Yii::t('app', 'NPV')?></h4>
<?php

Pjax::begin([
    'id' => 'finance-pjax-ajax-grid',
    'enablePushState' => false,
    'enableReplaceState' => false
]);
?>

    <?php

    echo TGridView::widget([
        'summary' => false,
        'enableRowClick' => false,
        'id' => 'finance-ajax-grid-view',
        'dataProvider' => $dataProvider,
        'tableOptions' => [
            'class' => 'table custom-table mt-3'
        ],
        'columns' => [
            'time',
            [
                'attribute' => 'income',
                'value' => function ($data) {
                    return $data->project->currency . $data->income;
                }
            ],
            [
                'attribute' => 'opex',
                'value' => function ($data) {
                    return $data->project->currency . $data->opex;
                }
            ],
            [
                'attribute' => 'cash_flow',
                'value' => function ($data) {
                    return $data->getTotalCashFlow();
                }
            ],
            [
                'class' => 'app\components\TActionColumn',
                'template' => '{update} {delete}',
                'header' => Yii::t('app', 'Actions')
            ]
        ]
    ]);
    ?>
<?php

Pjax::end();
?>
   </div>
	<div class="col-12">
		<h4 class="my-3 blue-back"><?=Yii::t('app', 'Calculation Results')?></h4>
		<div class="table-responsive table-finance">
			<table class="table table-hover m-b-0">
				<thead class="thead-dark">
					<tr>
						<th></th>
						<th><?=Yii::t('app', 'Description')?></th>
						<th><?=Yii::t('app', 'Value')?></th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<th><?=Yii::t('app', 'NPV')?></th>
						<td><p><?=Yii::t('app', 'A positive net present value indicates that the project earnings generated by a project or investment - in presentdollars - exceeds the anticipated costs, also in present dollars. It is assumed that an investment with a positive NPV will be profitable, and an investment with a negative NPV will result in a net loss')?>.</p></td>
						<td> <?php
    $project = Project::findOne(Yii::$app->request->queryParams['id']);
    if (! empty($project)) {
        echo $project->currency . Finance::getNpv();
    }
    ?>
                                                                        </td>
					</tr>
					<tr>
						<th><?=Yii::t('app', 'ROI')?></th>
						<td>
							<ul class="pl-3">
								<li><?=Yii::t('app', 'If ROI = 140%, you will make 40$ from 100$ of Investment')?></li>
								<li><?=Yii::t('app', 'If ROI =80%, you will lose 20$ from 100$ of Investment')?></li>
							</ul></td>
						<td> <?php
    echo Finance::getRoi();
    ?>
                                                                        </td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>