<?php

use app\components\grid\TGridView;
use yii\helpers\Html;
use yii\helpers\Url;

use app\models\User;
use app\modules\pms\models\Finance;

use yii\grid\GridView;
use yii\widgets\Pjax;
/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\modules\pms\models\search\Finance $searchModel
 */

?>
<ul class="list-unstyled d-flex">
	<li class="mr-3 w-25">
		<div class="border p-2 rounded-lg">
			<span>Annual Discount Rate :</span>
<?php
$model = \app\modules\pms\models\Rate::find()->where([
    'project_id' => Yii::$app->request->queryParams['id']
])->one();
if (! empty($model)) {
    echo $model->rate;
    $title = "Update Rate";
    $url = [
        'rate/update',
        'id' => $model->id
    ];
} else {
    $title = "Add Rate";
    $url = [
        'rate/add',
        'id' => Yii::$app->request->queryParams['id']
    ];
}
?>
</div>
	</li>
	<li> 
  
<?php
echo Html::a($title, $url, [
    'class' => 'btn btn-success mt-1'
]);

?>
   </li>
</ul>

<?php if (User::isAdmin()) echo Html::a('','#',['class'=>'multiple-delete glyphicon glyphicon-trash','id'=>"bulk_delete_finance-grid"])?>
<?php Pjax::begin(['id'=>'finance-pjax-grid']); ?>
  <?php

    echo TGridView::widget([
        'summary' => false,
        'enableRowClick' => false,
        'id' => 'finance-ajax-grid-view',
        'dataProvider' => $dataProvider,
        'tableOptions' => [
            'class' => 'table custom-table mt-3'
        ],
        'columns' => [
            'time',
            [
                'attribute' => 'income',
                'value' => function ($data) {
                    return $data->project->currency . $data->income;
                }
            ],
            [
                'attribute' => 'opex',
                'value' => function ($data) {
                    return $data->project->currency . $data->opex;
                }
            ],
            [
                'attribute' => 'cash_flow',
                'value' => function ($data) {
                return $data->getTotalCashFlow();
                }
            ],
            [
                'class' => 'app\components\TActionColumn',
                'template' => '{update} {delete}',
                'header' => '<a>Actions</a>'
            ]
        ]
    ]);
    ?>
<?php Pjax::end(); ?>

<div class="col-12">
		<h4 class="my-2">Calculation Results</h4>
		<div class="table-responsive table-finance">
			<table class="table table-hover m-b-0">
				<thead class="thead-dark">
					<tr>
						<th></th>
						<th>Description</th>
						<th>Value</th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<th>NPV</th>
						<td><p>A positive net present value indicates that the project
								earnings generated by a project or investment - in present
								dollars - exceeds the anticipated costs, also in present
								dollars. It is assumed that an investment with a positive NPV
								will be profitable, and an investment with a negative NPV will
								result in a net loss.</p></td>
						<td> <?php
						echo Finance::getNpv();
    ?>
                                                                        </td>
					</tr>
					<tr>
						<th>ROI</th>
						<td><p>
								Return on investment (ROI) is a financial metric that is widely
								used to measure the probability of gaining a return from an
								investment. It is a ratio that compares the gain or loss from an
								investment relative to its cost.It is as useful in evaluating
								the potential return from a stand-alone investment as it is in
								comparing returns from several investments.</br>For example,
							</p>
							<ul class="pl-3">
								<li>If ROI = 140%, you will make 40$ from 100$ of Investment</li>
								<li>If ROI =80%, you will lose 20$ from 100$ of Investment</li>
							</ul></td>
						<td> <?php
						echo Finance::getRoi();
    ?>
                                                                        </td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
<script> 
$('#bulk_delete_finance-grid').click(function(e) {
	e.preventDefault();
	 var keys = $('#finance-grid-view').yiiGridView('getSelectedRows');

	 if ( keys != '' ) {
		var ok = confirm("Do you really want to delete these items?");

		if( ok ) {
			$.ajax({
				url  : '<?php echo Url::toRoute(['finance/mass','action'=>'delete','model'=>get_class($searchModel)])?>', 
				type : "POST",
				data : {
					ids : keys,
				},
				success : function( response ) {
					if ( response.status == "OK" ) {
						 $.pjax.reload({container: '#finance-pjax-grid'});
					}
				}
		     });
		}
	 } else {
		alert('Please select items to delete');
	 }
});

</script>

